#!/usr/bin/env bash
#
# lineage uninstaller
# Usage:  curl -fsSL https://<host>/uninstall | bash
#         bash uninstall.sh
#
# Removes:
#   - $HOME/.lineage/                 (the installed source tree)
#   - $HOME/.local/bin/lineage        (the launcher, if it points at $HOME/.lineage)
#
# By default, runs without prompts (safe — it only touches lineage files).
#
set -euo pipefail

LINEAGE_HOME="${LINEAGE_HOME:-$HOME/.lineage}"
LINEAGE_BIN_DIR="${LINEAGE_BIN_DIR:-$HOME/.local/bin}"

if [ -t 1 ]; then
    BOLD=$'\033[1m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'
else
    BOLD=""; GREEN=""; YELLOW=""; RED=""; RESET=""
fi
info()    { printf "%blineage:%b %s\n" "${YELLOW}" "$RESET" "$*"; }
success() { printf "%b✓%b %s\n" "$GREEN" "$RESET" "$*"; }

removed=0

# Remove the installed source tree
if [ -d "$LINEAGE_HOME" ]; then
    info "removing $LINEAGE_HOME"
    rm -rf "$LINEAGE_HOME"
    removed=1
fi

# Remove the launcher only if it looks like it was generated by our installer.
# The shebang is on line 1, our marker is on line 2 — grep the whole file.
LAUNCHER="$LINEAGE_BIN_DIR/lineage"
if [ -f "$LAUNCHER" ] && grep -q "Auto-generated by the lineage installer" "$LAUNCHER" 2>/dev/null; then
    info "removing $LAUNCHER"
    rm -f "$LAUNCHER"
    removed=1
fi

# Also remove .bat on Windows-style installs (best effort)
LAUNCHER_BAT="$LINEAGE_BIN_DIR/lineage.bat"
if [ -f "$LAUNCHER_BAT" ] && grep -q "lineage installer" "$LAUNCHER_BAT" 2>/dev/null; then
    info "removing $LAUNCHER_BAT"
    rm -f "$LAUNCHER_BAT"
    removed=1
fi

if [ "$removed" -eq 0 ]; then
    info "nothing to remove (no lineage install found at $LINEAGE_HOME)"
else
    success "lineage uninstalled"
    echo
    printf "%bNote:%b you may also want to remove the PATH line added by the installer" "$BOLD" "$RESET"
    echo
fi
