"""Tests for install.sh / uninstall.sh.

These tests run the actual installer scripts in a sandbox tempdir using a
synthesized local tarball. They do not touch the real ``$HOME`` because
``LINEAGE_HOME`` and ``LINEAGE_BIN_DIR`` are overridden.

Windows (``install.ps1``) is not exercised here — there is no PowerShell in
the CI image used to run these tests. The Windows installer is kept structurally
parallel to ``install.sh`` so a future Windows test rig can cover it.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import tarfile
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
INSTALL_SH = REPO_ROOT / "install.sh"
UNINSTALL_SH = REPO_ROOT / "uninstall.sh"


# Skip the whole module on Windows — these scripts are POSIX-only.
pytestmark = pytest.mark.skipif(
    os.name == "nt", reason="install.sh / uninstall.sh are POSIX scripts"
)


def _have(cmd: str) -> bool:
    return shutil.which(cmd) is not None


needs_bash = pytest.mark.skipif(not _have("bash"), reason="bash not on PATH")
needs_tar = pytest.mark.skipif(not _have("tar"), reason="tar not on PATH")


def _build_fake_tarball(src_dir: Path, tarball_path: Path) -> None:
    """Create a tar.gz that mirrors the layout of a real GitHub release.

    GitHub release tarballs have a top-level directory named
    ``lineage-<version>/`` that contains the package contents. ``install.sh``
    uses ``--strip-components=1`` so that directory is removed during extract.
    """
    assert tarfile.is_tarfile.__name__  # touch the stdlib import for sanity
    with tarfile.open(tarball_path, "w:gz") as tf:
        # We add the package directly using a synthetic top-level name.
        # The installer's --strip-components=1 will handle the rest.
        for item in src_dir.iterdir():
            tf.add(item, arcname=f"lineage-test/{item.name}")


@needs_bash
@needs_tar
def test_install_sh_exists_and_is_executable():
    assert INSTALL_SH.is_file()
    mode = INSTALL_SH.stat().st_mode
    assert mode & stat.S_IXUSR, "install.sh must be executable"


@needs_bash
@needs_tar
def test_uninstall_sh_exists_and_is_executable():
    assert UNINSTALL_SH.is_file()
    mode = UNINSTALL_SH.stat().st_mode
    assert mode & stat.S_IXUSR, "uninstall.sh must be executable"


@needs_bash
@needs_tar
def test_install_local_tarball_creates_layout(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    """Run install.sh against a local tarball in a sandbox; verify the layout."""
    fake_home = tmp_path / "home"
    fake_home.mkdir()

    lineage_home = fake_home / ".lineage"
    bin_dir = fake_home / "bin"

    # Build a tarball that contains the actual lineage/ package.
    tarball = tmp_path / "lineage-0.1.0.tar.gz"
    _build_fake_tarball(REPO_ROOT, tarball)

    # Isolate from the real $HOME so the installer's PATH-advice code cannot
    # touch the real ~/.zshrc even by accident.
    monkeypatch.setenv("HOME", str(fake_home))
    monkeypatch.setenv("LINEAGE_HOME", str(lineage_home))
    monkeypatch.setenv("LINEAGE_BIN_DIR", str(bin_dir))

    # Stub the shell init file to a path inside the sandbox so the installer
    # does not write to the user's real rc file.
    fake_rc = fake_home / ".zshrc"
    monkeypatch.setenv("SHELL", "/bin/zsh")
    # Pre-create the rc file in the sandbox so the installer's test is
    # consistent with a real install (it appends to $HOME/.zshrc).
    fake_rc.write_text("# sandbox\n", encoding="utf-8")

    env = os.environ.copy()
    result = subprocess.run(
        ["bash", str(INSTALL_SH), str(tarball)],
        env=env,
        capture_output=True,
        text=True,
        timeout=60,
    )
    if result.returncode != 0:
        print("STDOUT:", result.stdout)
        print("STDERR:", result.stderr)
    assert result.returncode == 0, (
        f"install.sh failed:\n--- stdout ---\n{result.stdout}\n--- stderr ---\n{result.stderr}"
    )

    # Layout assertions
    installed = lineage_home / "0.1.0"
    assert installed.is_dir()
    assert (installed / "lineage").is_dir(), "package must be under <version>/lineage/"
    assert (installed / "lineage" / "cli.py").is_file()

    launcher = bin_dir / "lineage"
    assert launcher.is_file()
    assert launcher.stat().st_mode & stat.S_IXUSR, "launcher must be executable"
    launcher_text = launcher.read_text(encoding="utf-8")
    assert "Auto-generated by the lineage installer" in launcher_text
    assert str(installed) in launcher_text

    pin = lineage_home / ".current"
    assert pin.read_text(encoding="utf-8").strip() == "0.1.0"

    # The installed `lineage` should actually run.
    run = subprocess.run(
        [str(launcher), "--version"],
        env=env,
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert run.returncode == 0, run.stderr
    assert run.stdout.strip().startswith("lineage ")


@needs_bash
@needs_tar
def test_install_then_uninstall(tmp_path: Path, monkeypatch: pytest.MonkeyPatch):
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    lineage_home = fake_home / ".lineage"
    bin_dir = fake_home / "bin"

    tarball = tmp_path / "lineage-0.1.0.tar.gz"
    _build_fake_tarball(REPO_ROOT, tarball)

    monkeypatch.setenv("HOME", str(fake_home))
    monkeypatch.setenv("LINEAGE_HOME", str(lineage_home))
    monkeypatch.setenv("LINEAGE_BIN_DIR", str(bin_dir))
    monkeypatch.setenv("SHELL", "/bin/zsh")
    (fake_home / ".zshrc").write_text("# sandbox\n", encoding="utf-8")

    env = os.environ.copy()

    install = subprocess.run(
        ["bash", str(INSTALL_SH), str(tarball)],
        env=env, capture_output=True, text=True, timeout=60,
    )
    assert install.returncode == 0, install.stderr
    assert (lineage_home / "0.1.0").is_dir()
    assert (bin_dir / "lineage").is_file()

    uninstall = subprocess.run(
        ["bash", str(UNINSTALL_SH)],
        env=env, capture_output=True, text=True, timeout=30,
    )
    assert uninstall.returncode == 0, uninstall.stderr
    assert not lineage_home.exists(), "LINEAGE_HOME should be removed"
    assert not (bin_dir / "lineage").exists(), "launcher should be removed"


@needs_bash
@needs_tar
def test_uninstall_is_idempotent_when_nothing_installed(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
):
    """uninstall.sh should not error if there is nothing to remove."""
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    monkeypatch.setenv("HOME", str(fake_home))
    monkeypatch.setenv("LINEAGE_HOME", str(fake_home / ".lineage"))
    monkeypatch.setenv("LINEAGE_BIN_DIR", str(fake_home / "bin"))

    env = os.environ.copy()
    result = subprocess.run(
        ["bash", str(UNINSTALL_SH)],
        env=env, capture_output=True, text=True, timeout=30,
    )
    assert result.returncode == 0, result.stderr


@needs_bash
def test_install_rejects_windows_bash():
    """If uname reports a Windows-y string, install.sh should fail clearly."""
    if not _have("uname"):
        pytest.skip("uname not available")
    fake_home = Path("/tmp/lineage_uname_test")  # not actually used; we just want exit code
    env = os.environ.copy()
    env["LINEAGE_HOME"] = str(fake_home / ".lineage")
    env["LINEAGE_BIN_DIR"] = str(fake_home / "bin")
    # Force MINGW by overriding PATH to a shim that prints MINGW64_NT-10.0.
    shim_dir = fake_home / "shim"
    shim_dir.mkdir(parents=True, exist_ok=True)
    uname_shim = shim_dir / "uname"
    uname_shim.write_text("#!/usr/bin/env bash\necho MINGW64_NT-10.0\n", encoding="utf-8")
    uname_shim.chmod(0o755)
    env["PATH"] = str(shim_dir) + ":" + env["PATH"]
    result = subprocess.run(
        ["bash", str(INSTALL_SH), "/dev/null"],
        env=env, capture_output=True, text=True, timeout=10,
    )
    assert result.returncode != 0
    assert "install.ps1" in result.stderr or "Windows" in result.stderr
